apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-mall-ingress
  namespace: stride-suya
  annotations:
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - host: shopping-mall.dev-k8s.goorm.io
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: shopping-mall-v1-service
            port:
              number: 3000
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: shopping-mall-v2-service
            port:
              number: 3000